### ISSUE TITLE
Fails to compile on elixir 1.8 latest master

### ISSUE THREAD

**Issue by lukaszsamson** [plataformatec/nimble_csv#36]
I'm not sure if this is an error nimble_csv or a regression in elixir. 
```
== Compilation error in file lib/nimble_csv.ex ==
** (CompileError) lib/nimble_csv.ex:411: undefined variable "offset" in bitstring segment. If the size of the binary is a variable, the variable must be defined prior to its use in the binary/bitstring match itself, or outside the pattern match
    (elixir) src/elixir_bitstring.erl:197: :elixir_bitstring.expand_each_spec/5
    (elixir) src/elixir_bitstring.erl:168: :elixir_bitstring.expand_specs/6
    (elixir) src/elixir_bitstring.erl:41: :elixir_bitstring.expand/8
    (elixir) src/elixir_bitstring.erl:10: :elixir_bitstring.expand/4
    expanding macro: NimbleCSV.RFC4180.newlines_escape!/1
```

**Comment by josevalim** [comment]
Fixed in master and v1.8 branches, thank you!
